# Generated by Django 2.1.7 on 2019-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=50)),
                ('mot_de_pass', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
