# Generated by Django 2.1.7 on 2019-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_auto_20190310_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=50)),
                ('mot_de_pass', models.CharField(max_length=256)),
            ],
        ),
    ]
